# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# apiVersion: v1
# data:
#   mapUsers: |
#     - userarn: arn:aws:iam::211125635870:user/Ivanov-IAM
#       username: Ivanov-IAM
#       groups:
#         - system:masters
#   mapRoles: |
#     - groups:
#       - system:bootstrappers
#       - system:nodes
#       rolearn: arn:aws:iam::211125635870:role/prod-springboot-blue-green-node-group-role
#       username: system:node:{{EC2PrivateDNSName}}
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2025-02-09T20:41:40Z"
#   name: aws-auth
#   namespace: kube-system
#   resourceVersion: "3292"
#   uid: AIDATCKARRMPETHUQGIRX

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: AIDATCKARRMPETHUQGIRX
data:
  mapUsers: |
    - userarn: arn:aws:iam::211125635870:user/Ivanov-IAM
      username: Ivanov-IAM
      groups:
        - system:masters